version: yml.{build}
image: Visual Studio 2022
build:
  verbosity: minimal
platform:
- x86
- x64
configuration:
- Debug
- Release
before_build:
- cmd: git submodule init
- cmd: git submodule update
test_script:
- cmd: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" target\test\%PLATFORM%\%CONFIGURATION%\Tests.dll /logger:trx /Platform:%PLATFORM%'
- ps: |
    $wc = New-Object 'System.Net.WebClient'
    $files = Get-ChildItem -Path .\TestResults -Filter *.trx
    foreach ($file in $files) {
      $wc.UploadFile("https://ci.appveyor.com/api/testresults/mstest/$($env:APPVEYOR_JOB_ID)", (Resolve-Path ".\TestResults\$file"))
    }
artifacts:
- path: target\main\$(platform)\$(configuration)\Feeds.exe
  name: Feeds.exe
