#define	IDS_KEY_VALUE_SEPARATOR	100
#define	IDS_ERROR	101
#define	IDS_ERR_TOP_LEVEL	102
#define	IDS_ERR_ITEM_CONTENTS	103
#define	IDS_ERR_NO_SUCH_CHILD	104
#define	IDS_ERR_NO_ITEM_WITH_NUMBER	105
#define	IDS_ERR_FEED_CONTENTS_UNKNOWN	106
#define	IDS_ERR_FOLDER_DETAILS_UNKNOWN	107

#define	IDS_TITLE	112
#define	IDS_PROMPT	113

#define	IDS_DETAILS_ITEM_AUTHOR	128
#define	IDS_DETAILS_ITEM_LINK	129
#define	IDS_DETAILS_ITEM_COMMENTS	130
#define	IDS_DETAILS_ITEM_ISREAD	131
#define	IDS_DETAILS_ITEM_ENCLOSURE	132
#define	IDS_DETAILS_ITEM_PUBDATE	133
#define	IDS_DETAILS_ITEM_MODIFIED	134
#define	IDS_DETAILS_ENCLOSURE_TYPE	135
#define	IDS_DETAILS_ENCLOSURE_URL	136
#define	IDS_DETAILS_ENCLOSURE_DOWNLOADSTATUS	137
#define	IDS_DETAILS_ENCLOSURE_LOCALPATH	138
#define	IDS_DETAILS_ENCLOSURE_LASTDOWNLOADERROR	139
#define	IDS_DETAILS_ENCLOSURE_DOWNLOADMIMETYPE	140
#define	IDS_DETAILS_ENCLOSURE_DOWNLOADURL	141

#define	IDS_DETAILS_FEED_ITEMCOUNT	144
#define	IDS_DETAILS_FEED_UNREADITEMCOUNT	145
#define	IDS_DETAILS_FEED_MAXITEMCOUNT	146
#define	IDS_DETAILS_FEED_DOWNLOADSTATUS	147
#define	IDS_DETAILS_FEED_LASTDOWNLOADERROR	148
#define	IDS_DETAILS_FEED_PUBDATE	149
#define	IDS_DETAILS_FEED_LASTBUILDDATE	150
#define	IDS_DETAILS_FEED_LASTDOWNLOADTIME	151
#define	IDS_DETAILS_FEED_IMAGE	152
#define	IDS_DETAILS_FEED_LINK	153
#define	IDS_DETAILS_FEED_DOWNLOADURL	154
